### ISSUE TITLE
Better namespace handling and chaika tags

### ISSUE THREAD

**Issue by wtfabear** [Difegue/LANraragi#106]
This is regarding the tag being used to populate the "Series" column on the main library page. I didn't see this documented anywhere, but it seems like LRR uses the first "parody:" tag to determine the Series of a gallery. This works well for doujins, but doesn't make a whole lot of sense for original h-manga. The default auto tagger will grab the magazine name from the file name and set that as "parody:". Using a namespace like "magazine:" would make more sense and be in line with how chaika handles fakku magazine comics. 

Not sure if should be in a separate issue as well, but I noticed chaika archive and gallery pages can have different tags, with the gallery page being more complete. Example:

https://panda.chaika.moe/archive/21493/
vs 
https://panda.chaika.moe/gallery/15195/

**Comment by Difegue** [comment]
To populate the column, we look for either parody: or series:, so that's not really an issue.  
The autotagger hasn't been touched in a while though and indeed does use parody: as default.  

I use the E-Hentai file name standard for auto-tagging and don't really plan on moving away from it: 
`(Release) [Artist] TITLE (Series) [Language]`
As such, moving the default parsed namespace from "parody:" to "magazine:" would work for chaika/fakku scans, but not for anything else. It also would look kinda weird in the Series column, wouldn't it?  
For now, I recommend you disable the auto-tagger if you upload mostly Chaika/Fakku scans.  

For your last question, we perform searching in archive pages by default, but the user can use gallery URLs in overrides when editing a single archive. Chaika's search API only returns archives by default, but we can use the API to retrieve the matching gallery ID and then look for metadata in that. I'm not a big chaika user so I'll ask before making the work:
* Do all archives have a matching gallery page?
* Do galleries consistently have more/better metadata than archives?

**Comment by wtfabear** [comment]
Maybe have "series:" be the default namespace for the autotagger then? I find the autotagger useful for getting the CXX event tag, which goes untracked by both panda or chaika.

* Do all archives have a matching gallery page?
I don't know how to exhaustively check this as a simple end-user of the website, but I spot-checked the oldest archives based on added date and they all seem to have a gallery url associated with them in the "metadata" field on the archive page. Maybe someone with more experience than me can correct me, but from observation it looks like chaika gallery entries are created first, then associated archives are made available and linked at a later date once the archive is located and collected. This is based on their missing archives page: https://panda.chaika.moe/missing-archives/

If this is true, then every archive should have a gallery page.

* Do galleries consistently have more/better metadata than archives?
I don't know and can't check exhaustively. I haven't seen anything that contracts this though.

**Comment by Difegue** [comment]
I needed to fix up sha-1 in chaika anyways, so I went ahead and added logic for galleries too.  
Not gonna make a release until 0.6, but you can sideload the Chaika.pm file and it should work ok.  

(Test suite is currently broken due to Docker shenanigans in #99 )

**Comment by Difegue** [comment]
As for multiple series/parody tags, I'll keep it in mind -- might get to it when I do the search revamp in #80 .

**Comment by Difegue** [comment]
oh hey I fixed the test suite 69a37147c5eaf3a4a173e81d569b9096e9d12397

**Comment by wtfabear** [comment]
I just throught of something: what if you simply included the magazine: namespace to be used for the series column (if available)? The scenario here is grabbing tags from chaika for fakku galleries. All of these galleries will have the magazine: namespace.

**Comment by Difegue** [comment]
It's still a bit weird having stuff under magazine: show up in the Series column, but I can add them as a fallback if neither parody: or series: is available.
