### ISSUE TITLE
[API] Add file path field for archive info

### ISSUE THREAD

**Issue by vuhe** [Difegue/LANraragi#1061]
I want to create an API based proxy for customizing reading lists based on tags and improving image quality.

Because I want to deploy on the same host, calling the download API will result in unnecessary file copying, especially if the files are too large.

It seems that there is file path information in the database. Can we add a file path field in the archive information API? This should solve most of the problems.

**Comment by Difegue** [comment]
👋 I've avoided exposing the filepath in the API since it's (technically) private information about the host machine that shouldn't matter to clients. Also, filesystem encoding can be tricky and the API defaults to UTF-8, so you wouldn't necessarily have correct path information. 

If you're running on the same host, I believe you could just hit the redis database directly, or keep your own ID->file map on the proxy side; LRR IDs are fairly easy to calculate compute-wise.
