### ISSUE TITLE
Few proposed improvements (core)

### ISSUE THREAD

**Issue by CirnoT** [Difegue/LANraragi#157]
- Category support (something like this https://github.com/Difegue/LANraragi/compare/dev...CirnoT:category?expand=1)
- Ability for E-Hentai plugin to fetch URL from source tag and directly querying API (this would be obviously disabled if user provided URL in edit form but otherwise should be the first thing plugin tries before searching site.) This could be useful to easily fetch additional metadata or tags for already tagged archived (right now doing it via batch tagger is error prone as it ignores URL that was provided [corrected] manually [because detected gallery was wrong or plugin wasn't able to find it])

**Comment by Difegue** [comment]
I'm planning for categories to be customizable by users instead of copying the old E-H list.  
(I'm supposed to talk about that in that survey results blog post I've been writing, but I've been incredibly strapped for time those last few days.)  

For the E-H plugin thing, it's indeed a pretty good improvement since source: tags can be obtained elsewhere, and the E-H API doesn't care about sadpanda access as long as you have the correct gallery ID/Key.
