### ISSUE TITLE
Swap inotify to a cross-platform change detection module (macOS compatibility)

### ISSUE THREAD

**Issue by Bl4Cc4t** [Difegue/LANraragi#158]
Hey there,
the module `Linux::Inotify2` does not work under macOS.
Would it be possible to substitute it for an alternative? Maybe an universal module would work better, i.e. `File::ChangeNotify` or something along the lines.

I would’ve liked to create a pull request, but I’m too inexperienced in this language. :/

**Comment by Difegue** [comment]
I didn't know inotify wasn't a thing on macOS, although in hindsight it makes sense: It's a kernel feature and while Darwin is unix, it's not linux at all.  

I'm crumbling under new issues since the panda shutdown, so I probably won't be able to allocate resources to swapping the inotify module for the time being.

**Comment by Bl4Cc4t** [comment]
Understandable. I’m looking forward nevertheless!

**Comment by Difegue** [comment]
`File::ChangeNotify` seems to actually use `Inotify2` as the backend on Linux, so I can probably work this in without having to test the app to hell and back for breaking changes.  

I'll try tackling this now. (Thought about going for the OPDS issue first but I'll leave it up for grabs a little while longer since it's a pretty fun first issue I think)

**Comment by Difegue** [comment]
I did some quick testing with the ChangeNotify module, but it doesn't seem to handle subdirectories as well as it advertises -- plopping a subdirectory in the content folder doesn't seem to actually add it to the watchlist. It doesn't raise events for the files in the subdirectory either.  

I pushed what I did to a spare branch so you might be able to experiment with that.

**Comment by Bl4Cc4t** [comment]
I now succeeded in installing it – it was a bit complicated.
I had trouble with `Archive::Extract::Libarchive` and `Archive::Peek::Libarchive`, they did not want to find `libarchive`. Peek missed the `PKG_CONFIG_PATH`, Extract the `CFLAGS`.
In the process of debugging, I found out that `cpan` ignores the `CPPFLAGS`, which irritated me for quite some time.

**Comment by Difegue** [comment]
Some further testing later:  

  | Add file | Add subfolder | Delete file | Delete subfolder
-- | -- | -- | -- | --
Linux (inotify) | ✅ | ❌ | ❌ | ❌
Linux (default) | ✅ | ✅ | ✅ | ✅
WSL (inotify) | ✅ | ❌ | ✅ | ❌
WSL (default) | ✅ | ✅ | ✅ | ✅  

I was expecting the inotify watcher to work properly on a regular *nix machine, but apparently not?  
Default works everywhere and seems good enough for my case, I might just force its usage every time as an easy solution.

**Comment by Bl4Cc4t** [comment]
by default, you mean `File::ChangeNotify::Watcher::Default`?
If so, then we are good to go :D

**Comment by Difegue** [comment]
Alright, done! I'll merge this alongside the homebrew stuff when #221 is resolved.
