### ISSUE TITLE
Implement an API endpoint exposing the Archive Library as an OPDS Catalog

### ISSUE THREAD

**Issue by Yangrixiao** [Difegue/LANraragi#201]
sorry，My English is very poor，Maybe not expressing well。

**Comment by Difegue** [comment]
Hello,

The initial request was a bit lacking in info, so I did some extra research:  
https://en.wikipedia.org/wiki/OPDS  
OPDS (Open Publication Distribution System) is a standard based on Atom, which allows a server to expose a catalog of ebooks/digital content. The standard is seemingly supported by Calibre and multiple ebook readers. 

It's interesting! I wouldn't mind having support for an endpoint that'd expose the archives in a LRR instance this way. 

I suppose [OPDS 1.2](https://specs.opds.io/opds-1.2) would be the best version of the spec to implement in order to target the most devices. Did you have any devices/software readers in mind that'd benefit from having an OPDS catalog to use?

**Comment by Yangrixiao** [comment]
I am very happy that you are interested in this proposal.
i have only android devices，so i can tell you android software。（perfect viewer）Is a speaicl software  to watching comics，support opds，but i don't know the opds version。
and also （mooreader）support: EPUB, PDF, DJVU, AZW3, MOBI, FB2, PRC, CHM, CBZ, CBR, UMD, DOCX, ODT, RTF, TXT, HTML, MD(MarkDown), WEBP, RAR, ZIP, OPDS

**Comment by Difegue** [comment]
I'll try to get this done in 0.6.6.

**Comment by Yangrixiao** [comment]
thanks very much！！

**Comment by CirnoT** [comment]
I strongly believe 0.6.6 should be released before this is merged due to sheer amount of changes it introduces already. This is very niche feature which can wait for another release.

**Comment by Difegue** [comment]
This is a fairly isolated feature which I'd like to provide in preview form to get some feedback.

**Comment by CirnoT** [comment]
I'd say nightly versions are for previewing features, stuff that's in releases should be finished.

**Comment by Difegue** [comment]
The OPDS implementation is now complete.  

I based myself on spec 1.2 and managed to get a fair bunch of clients working after some testing.  
I don't have iOS devices to test but apparently Chunky Reader works well there.  
Nothing for Linux: Calibre+opds-reader lists the books but can't download them.  

I initially thought OPDS for comics was very lacking and basically unused, but there's a fair bit of support already there. (thanks ubooquity I suppose)  

Leaving this open until I get to writing the documentation.

## Android  
**Moon+ Reader**
![image](https://user-images.githubusercontent.com/8237712/67971518-35450180-fc0d-11e9-9e6c-fa05fb2194b2.png)
![image](https://user-images.githubusercontent.com/8237712/67971532-3aa24c00-fc0d-11e9-8139-efdadb8d7d65.png)

**Librera Reader**
![image](https://user-images.githubusercontent.com/8237712/67971550-3f670000-fc0d-11e9-9e4e-dc3dcf9f91a2.png)

**Challenger Comics Reader**
![image](https://user-images.githubusercontent.com/8237712/67971593-5574c080-fc0d-11e9-99c9-f263e43719dd.png)

## Windows
**AlfaReader**  
![image](https://user-images.githubusercontent.com/8237712/67971627-61f91900-fc0d-11e9-858f-48d06fa8cd00.png)

**Comment by Difegue** [comment]
https://sugoi.gitbook.io/lanraragi/v/dev/advanced-usage/external-readers  

Done.
