### ISSUE TITLE
App not loading after power-failure/reboot since 4.5

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#24]
Hello
I can't seem to re-run the app after a power-failure/reboot since 4.5. I get a "The connection to the server was reset while the page was loading." error on localhost:3000 in my browser.
For reference I'm using the Vagrant installation and the command line dosen't throw any errors when I give it the vagrant up command to boot LANraragi. Right now I'm deleting the VM and reinstalling on every boot.
Anything you could suggest?

**Comment by Difegue** [comment]
As of 0.4.5, the Vagrant setup is essentially a thin VM around the LANraragi Docker container.
On the first vagrant boot(commonly known as the provisioning stage), said container is downloaded and parametered (and therefore, started at the same time.)

Your issue sounds like the container is not being restarted on subsequent `vagrant up`s.  
Which is very odd, since the Vagrant wrapper is supposed to start the container every time.  

....At least that's how it's advertised!  Additional research certainly makes it look like [Vagrant isn't doing its job.](https://stackoverflow.com/questions/31623916/vagrant-docker-provisioner-doesnt-start-containers-on-boot)

I'll push a modified Vagrantfile soon with the specified fix.

**Comment by Difegue** [comment]
The commit above should fix things - Tested a `vagrant halt`/`vagrant up` combo and had no issues.
Tell me how it goes on your side!

**Comment by xd1986k** [comment]
The machine does boot up but my archives(in the content folder) are missing. Newly uploaded archives also don't appear. I have the following in my log. 

>  [LANraragi] [warn] Delete the shinobu-lock file if you just started LANraragi.
[LANraragi] [info] Lockfile present in dev mode - Background worker not respawned.

**Comment by Difegue** [comment]
Oh shit, the lockfile. Forgot about the issues it could bring in a Docker environment - Glad I put those logs there though.

The archives missing is due to the recent commit b521dc1b762c3fd78abb974a07842fdc9175cc4f, which changed ID generation. They should be coming back instantaneously thanks to the background worker, which in this case is not being started (due to the lockfile)

I introduced that lockfile to speed up development by not restarting the background worker all the time(devmode autorestarts the entire server on every file modification), 
Since the current docker images are based on the current raw git code, they're in dev mode by default, which introduces that issue. The lockfile isn't deleted, and the worker never comes back.

You "could" ssh into the vagrant machine, then open up a command line on the docker container to delete the lockfile, which should solve all those issues... Until the next time.

I'll fix those issues in an upcoming commit. Sorry for making you rebuild the entire VM once again.

**Comment by xd1986k** [comment]
I'll wait. It's not that pressing. No worries about rebuilding either. Gotta use bandwidth for something.

**Comment by Difegue** [comment]
78a50c740bfc4617dd5e7d22e5b1e9e3fcbe3551 moves the devmode setting from lrr.conf to the database.  
This makes it so all new installations of LRR default in production mode, and devmode is fully opt-in.  

As an extra safety mesure, switching to production mode deletes any old lockfile laying around, as a way to clean the state. (Even though lockfiles aren't considered at all in prod mode)  

This should be enough to solve this problem.

**Comment by xd1986k** [comment]
Works now. There seems to be a new problem. Uploaded archives show in the app but not in the content folder. Also files in content folder are not detected. Can you reproduce this?

**Comment by Difegue** [comment]
Looks like the content folder has been assigned to somewhere inside the VM.
What does its path look like on the configuration page? I'll respin a vagrant machine to see if I can reproduce this.

**Comment by Difegue** [comment]
After some more tests, it looks like the content folder isn't being synced to the folder on the VM on subsequent vagrant ups. Goddammit Vagrant.

(Also met up with some errors while opening archives with unicode characters, which might be related to #22. For some reason this only happens within a Vagrant context...)

**Comment by Difegue** [comment]
I pushed some Vagrantfile enhancements in the latest commit. subsequent `vagrant halt`/`vagrant up`s seemed to keep the content folder synced just fine.

Look out for the mount notification from VirtualBox when starting the vagrant machine:
<pre>[default] GuestAdditions 5.1.26 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => [content folder]
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.</pre>

**Comment by xd1986k** [comment]
Does not seem to be working. I do get the mount notification.

> ==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => D:/Portable/LANraragi
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

But the machine seems to revert to stock settings and internal content folder(i.e unsynced) on restarting.
There is happy news though. On a whim, I ran vagrant provision and that fixes it. I can deal with one extra step.

**Comment by Difegue** [comment]
Do you have to run vagrant provision each time? It should only be meant for updating the internal Docker image.  
I just tried a vagrant up on a freshly rebooted machine and the folder was synced without issues.

**Comment by xd1986k** [comment]
Yep. Maybe it's something on my end.

**Comment by xd1986k** [comment]
It just started working all of a sudden so I guess it was some problem on my end.

**Comment by xd1986k** [comment]
I figured out the problem. Provisioning is only required when LANraragi is not "gracefully" shut down (power outage in my case).

**Comment by Difegue** [comment]
I've been encountering similar issues on my own personal build running Docker - Sounds like their restart policies aren't working properly.  

I'll do a bit more research, but it doesn't look like much can be done on my side.
