### ISSUE TITLE
[Suggestion] Scrollable Reader

### ISSUE THREAD

**Issue by NO-ob** [Difegue/LANraragi#242]
Would it be possible to have a feature added to load all images on a single page and be able to scroll down them at some point in the future please
Theres a userscript for exhentai called ehunter which does it if you dont understand what i mean https://github.com/hanFengSan/eHunter

**Comment by Difegue** [comment]
It's certainly possible! Just needs some javascript work to add it as an extra reader option.  

Currently the reader already has all the URLs to the images when opened, so someone could probably even implement this as a userscript if they really wanted it.

**Comment by NO-ob** [comment]
I made a script, took me way longer than i'd like to admit kek https://github.com/NO-ob/LanraragiScroll

**Comment by Difegue** [comment]
Looks good! I think you could've used the `pageNumber` variable which is already normally declared instead of scraping the DOM to get the total page count, but that certainly works.  

A proper implementation would be better and I'll probably get to it one day, but it's great to have the userscript here in the meantime for anyone who wants the feature. Thanks a lot! 👍

**Comment by NO-ob** [comment]
Thanks I've changed it to use pageNumber now, also made it toggleable

**Comment by Difegue** [comment]
As part of the recent Reader refactoring, infinite scrolling is now built-in! 🎉
