### ISSUE TITLE
Feature Request: Serve resized images to clients

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#245]
While this is likely quite long-term, and only really serves a purpose for people viewing LRR remotely from mobile or otherwise limited connections, I would love to see a feature to be able to resize images on the server, before serving them to a client if the images are over a specified size.

Ideally, there would be an option to only resize images if the client was accessing LRR from a remote ip address, so local access would be unaffected. If that's not feasible, then toggle in the settings would be enough.

Rather than just blanket compressing everything to jpg, I would also like to see aspects from the source images remain in place. For instance, if the gallery has PNG black and white pages with limited colors to save space e.g 32 colors, then LRR would keep the colors at 32, and just resize the image to be smaller. And if it was a full color png, it would compress to jpg. This would do a lot for keeping sizes down and quality up.

**Comment by Difegue** [comment]
Related to #238 ... a lot!
This feature was actually present in old versions but was removed when the move to Image::Scale for thumbnails happened.
Some code related to it is still in the codebase so hooking it back wouldn't be too complex whenever we move back to using Magick. 

iirc, the original implementation was to simply apply a 50% compression algorithm to images that went past a filesize parametered in settings.

**Comment by Difegue** [comment]
Took a code infusion from 0.3.0 and brought this back. I was wrong about the original implementation: You can also tweak the compression rate in settings, instead of it being fixed at 50%.  

The compression is mapped to the `quality` attribute in magick, which is only really effective for jpeg files. So for now, this implementation does convert everything to jpeg. Sorry 'bout that. 😅  

I think it's good enough as a starting point -- The compression algorithm can be tweaked/iterated later to add special handling for pngs.
