### ISSUE TITLE
Feature Request: Move galleries with specific tags to a specified folder

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#253]
This might be completely out of scope, but I've been thinking about this for awhile and would like to know if you think it's feasible. I'd be happy to donate $50 if it were to be added.

**Background**
As my archive has grown into the thousands trying to sort galleries with specific tags into folders becomes more and more time consuming. And I only have a few tags that I bother sorting! If LANraragi could do that automatically... how amazing would that be? It also has a nice side effect of if a user were to upload a gallery it will be sorted properly without them needing to have access to the servers file-structure.

**Implementation**
Have users create a list of rules, each with one or multiple user defined tags e.g `language:english, parody:fate_stay_night` and then you would set the path the gallery moves to if it matches that rule, e.g `/english/parody/fate/stay night`. Each rule would have a definable priority level (1-5) so in the case of multiple rules being matched to one gallery LRR just picks the highest priority rule. If it matches multiple rules with the same priority level, then either ask the user or do nothing and write an error. 

Ideally you should also be able to prevent LRR from moving galleries if they are in a blacklisted folder because some people might have e.g a folder for incomplete or purged galleries which they want to keep separate.

And while this is optional, if it could work with wildcards, that would be very handy for things like:
`parody:*` > `/parody` And (not sure if this would even work): `parody:*, parody:*` > `/parody/various` or `parody:fate*, parody:fate*` > `parody/fate/various`. But i don't want to make this more complicated than it probably already is. 

If setting priority rules is too hard, asking the user which rule to use when a gallery matches multiple rules would work as well, although not ideal since it would slow things down a lot.

**Outcome**
Imagine just dropping a huge batch of files onto LRR's library, and having it sort them all automatically as each galleries meta-data is read and ran through the rule-set. That would be a huge time-saver for anyone who cares about sorting their gallery.

**Comment by Difegue** [comment]
![33ad6305454e3c95438f405ca5127aeaecd1608a8189abeefbc23c3942bae241](https://user-images.githubusercontent.com/8237712/73137878-09df8080-405d-11ea-9a5a-9affc3bf46fa.jpg)  

Yeah, I'll have to say this goes far off the scope as far as I'm concerned -- While it would be possible within the current design since it's just shuffling files around, I really don't consider keeping/creating a folder structure parallel to what we store in database an essential feature.  

If you want something like this, it'd probably be better to write a script/program that consumes the API to see the tags assigned to each file, and then moves the files.

**Comment by Asinin3** [comment]
Yeah i thought it would probably be out of scope, oh well.
