### ISSUE TITLE
[Bug] Shinobu not responding to new archives if they are added in folders

### ISSUE THREAD

**Issue by Mayriad** [Difegue/LANraragi#276]
*This issue comes from #274 my big list of LRR bugs and suggestion. Please refer to that to see details of my setup and usage.*

**LRR Version and OS**

LANraragi for Windows 0.6.9 (MSI installer) on Microsoft Windows 10 version 10.0.18363.720. Archives are located on a NAS and accessed via a mount point in the content folder.

**Bug Details**

LANraragi watches and accesses my archives via a mount point in the content folder. However, no matter where I add the archives, as long as I move them into the content folder in folders, Shinobu will not respond to these new archives in folders even though its status is still "OK!" in the admin settings. There is no log to provide.

So, Shinobu will not react if I add archives in folders. Shinobu does react if I add the same archives to the same place without placing them inside folders.

**Comment by Difegue** [comment]
I'm pretty sure this is a WSL-only issue -- The file detection is a bit dodgy there for the moment, I'm waiting for WSL2 to hit General Availability to do some further tests.

**Comment by Asinin3** [comment]
I am a bit confused about this report, not completely sure I'm understanding the issue. Because LRR can pick up all the archives I put in my library regardless of if they are in the root of the library i told LRR to scan, or if i place an archive file within a subfolder.

I am on Windows 10 Enterprise 1909 and using LRR through WSL. But the files are all stored locally on my machine, perhaps it's an issue with having the files hosted externally? Are you connecting to the nas over a samba share or?

**Comment by Mayriad** [comment]
> Because LRR can pick up all the archives I put in my library regardless of if they are in the root of the library i told LRR to scan, or if i place an archive file within a subfolder.

This sounds like you are directly placing archive files somewhere inside the content folder; if I do this the archives will be picked up too. The problem happens when I place a folder containing archives somewhere inside the content folder, and Shinobu will not react to the archives inside that folder.
 
> I am on Windows 10 Enterprise 1909 and using LRR through WSL. But the files are all stored locally on my machine, perhaps it's an issue with having the files hosted externally?

Nope, the problem happens no matter where the folders are placed.

**Comment by Difegue** [comment]
I've added a toggle for WSL2 in a recent nightly build, which might help with this:  

![image](https://user-images.githubusercontent.com/8237712/96473448-f3ec9e00-1231-11eb-8b27-19d89b43d64d.png)

**Comment by Mayriad** [comment]
Thanks. I will test this again along with #282 when I get time.

**Comment by Mayriad** [comment]
I still have the same problem using 0.7.5 with the WSL 2 option enabled. Of course, I am using WSL 2 myself. I have to restart file watcher to trigger the detection of new files. My setup is probably just too weird.

**Comment by Asinin3** [comment]
I have galleries inside my main content folder's root directory as well as inside subfolders, and have never had this problem.

**Comment by Difegue** [comment]
Gonna close this as wontfix for now, I suppose the issue stems from the network drive mounting not necessarily handing over all the required filesystem events for shinobu's inotify to work properly.  

Not much can be done on my end, I suggest for future users reading this issue to install LRR on the NAS directly instead of locally on the windows machine if you want filesystem stuff to work properly.

**Comment by Mayriad** [comment]
👍
