### ISSUE TITLE
[Bug] Empty tag blacklist not saving

### ISSUE THREAD

**Issue by Mayriad** [Difegue/LANraragi#278]
*This issue comes from #274 my big list of LRR bugs and suggestion. Please refer to that to see details of my setup and usage.*

**LRR Version and OS**

LANraragi for Windows 0.6.9 (MSI installer) on Microsoft Windows 10 version 10.0.18363.720. Archives are located on a NAS and accessed via a mount point in the content folder.

**Bug Details**

For some reason, the tag blacklist in the admin settings cannot be empty, which means LANraragi requires the user to omit some tag(s). Saving the admin settings when this field is empty will reset this field to the default list of tags. The debug log will say:

```
[LANraragi] [debug] Saving blacklist with value
```

It does not throw an error, but there is nothing after "value". I think that is the problematic part, because the function handling the blacklist expects a non-empty string like the default below:

```
[LANraragi] [debug] Saving blacklist with value already uploaded, forbidden content, incomplete, ongoing, complete, various, digital, translated, russian, chinese, portuguese, french, spanish, italian, vietnamese, german, indonesian
```

**Comment by Difegue** [comment]
There's a failsafe when saving options in the app to reset blank fields to their default value.  
This works very well everywhere -- except for the blacklist which is one field you might want to have blank.  

Since I don't want to remove said failsafe, I added a toggle to disable blacklisting entirely instead. It should do the job.
