### ISSUE TITLE
Folder sorting with external reader

### ISSUE THREAD

**Issue by Hotmany** [Difegue/LANraragi#288]
Hello,

First I'm sorry if this is not the place to ask this. I discovered LANraragi a few days ago and I always looked for something like that, thank you all for your work.

I learned to setup the software and I decided to go with an external reader to read on my phone and tablet, I'm using Tachiyomi right now. Everything works except the structure of my folder.

For example I have my LANraragi folder, then inside folder AAA-BBB for each manga and inside each folder I have AAA 01.cbz AAA 02.cbz and so on. But in Tachiyomi it shows me every file individually and do not group them by folder.

So I wanted to ask if it was possible to "sort" by folder somewhere ? The batch tagging doesn't work, it tells me there's no match or no json file and when I try to edit files individually there's no section to group multiple files in one category.

There's probably something that I didn't do or didn't understand but after a few hours trying to find the solution by myself I can't seem to find the answer.

Thank you by advance and sorry again if I'm not in the right section.

**Comment by Difegue** [comment]
Hello,  

Sorting in folders/categories is a missing feature currently (well it's been missing for a while, not gonna lie), so at the moment what you're asking for isn't possible. See #33 .  

This is a pretty glaring hole in the featureset so I am going to have to implement it at some point - Still not really sure how though. 😶

**Comment by Difegue** [comment]
I've added categories as of the latest release, alongside a script allowing users to automatically create them from their folder hierarchy, if they have one.  
![image](https://user-images.githubusercontent.com/8237712/81989653-efe2a180-963d-11ea-89d7-6659168a8526.png)  

External readers will need to implement the new 0.7.0 APIs once it releases in order to leverage this feature, which hopefully shouldn't take them too long. 🙂 Closing this on my side for now.
