### ISSUE TITLE
Nightly running as root even with LRR_UID and LRR_GID set to custom value

### ISSUE THREAD

**Issue by Guerra24** [Difegue/LANraragi#309]
Logs say
`Starting LANraragi with UID/GID : 1001/1001`
But htop says.
![image](https://user-images.githubusercontent.com/9023392/82308589-3823fb80-997f-11ea-84bb-182d9620391d.png)
And thumbnails.
`-rw-r--r-- 1 root     root      56808 May 19 03:08 e62f79cb3c7622cc8a615e0692b0895be8d38271.jpg`

Database file is also root owned.

Is this expected? Files are written as root owned which is problematic. Before the s6-overlay change  it ran as whatever user was set in both envs.
Restarting the container runs the chown command and restore the user:group back but that is not ideal.

**Comment by Difegue** [comment]
Nah, s6 should run the underlying services as the provided users, so this is a problem.  
I'll do some digging on my own later, but @alexwh might have an idea.

**Comment by koma-cute** [comment]
Turns out there's not one, not two but three stupid mistakes here.

First of all is using envuidgid which just sets the UID/GID envvars, letting the program take care of the rest.

Second is not executing the program with the tool itself (I was under the impression it was an exec/fork like action).

Third is HOME being exported in the wrong place, when copied over from the old entrypoint.sh script, causing perl's "attepting to create /root/perl5"... thing... to fail.

Made #310 to hopefully fix these issues.
