### ISSUE TITLE
[Feature Request] Add base url support

### ISSUE THREAD

**Issue by fullmetal1** [Difegue/LANraragi#363]
The purpose is to provide the ability to run lanraragi behind a reverse proxy as a subpath of a domain instead of a subdomain, since many free services do not allow ddns domains to have subdomains.

**Comment by Difegue** [comment]
According to the links in the [previous issue](https://github.com/Difegue/LANraragi/issues/32) we touched upon this subject, implementation could be as simple as adding a hook if a base url is configured:  

```
app->hook( before_dispatch => sub {
        my $c = shift;
        unless ($c->req->url->path->to_route =~ m#/baseurl#) {
            $c->req->url->path( "/baseurl" . $c->req->url->path->to_string);
        }
    } );
```
(https://stackoverflow.com/questions/25170147/base-url-in-mojolicious-template-rendering)  

The bigger question is where to put the base url config?  
I honestly don't think this is a setting that would be used much, and it can't be set from the web interface since you likely won't have access to it, so it'd probably be fine in `lrr.conf`. Might also want to add an environment variable override for Docker users?

**Comment by fullmetal1** [comment]
You already have a hook into before dispatch, and that module has access to the LANraragi settings module. I was testing it out but couldn't understand mojolicious' url object. Had some wierd behaviour with url->base that would make it use the wrong address, and also the web app pages didn't seem to exist at the rewritten locations.I couldn't figure it out after a few hours.

**Comment by Difegue** [comment]
Oh yeah, the SIGTERM catcher does hook in before_dispatch.  
You can add code in there no problem but I still think it'd be better/easier to put the base url setting in lrr.conf, you could then access it with something as dumb as `$config->{base_url}`.  

If you can't get stuff working in a hook, I think `Routing.pm` would also be an acceptable place to try? You could store the base url setting in a string (defaulting to empty of course) and prepend that to each routed URL path.

**Comment by alethiophile** [comment]
I'm currently looking to deploy LANraragi behind a reverse proxy under a base URL path, so I thought I would look at this issue and see what can be done about it.

The underlying requirement is to prepend the configured base URL path to every link LANraragi generates, including all the static files. You can do this for links generated via `url_for` with the hook code mentioned above. However, one big problem is that the templates and the frontend JS are all littered with hard-coded URL strings, meaning every one of those would have to be altered accordingly -- either to use `url_for`, to depend on a central base URL variable, or (depending) to use a path-relative URL.

I'm willing to work on this, but it would also require discipline going forward: every URL reference in the entire app must use the appropriate construction method, and no hard-coded absolute path URLs must be used, or else it would be broken under a base URL. Is it feasible to make this a requirement?

**Comment by alethiophile** [comment]
Relative URLs are certainly the simplest. One problem with that is that a relative URL introduces a hidden dependency between the URL string specified and the route that the page is served under. (E.g. some pages would need URLs with `./api/stuff` or just `api/stuff`, others would need `../api/stuff`, depending on what the page URL is.) It might be better overall to standardize on using `url_for` or equivalent, to avoid that source of potential errors.

I'll poke around at the code and submit a pull request sometime soon.

**Comment by absinthe4869** [comment]
I've tried to deploy the latest version with the base URL. I'd like to share the problems I met and hope this will be helpful to make LANraragi better.

The current version I use is v0.9.60, deployed with Podman, using base URL "/lanraragi".

- The doc about base url should be updated

I can not make it when I follows the guideline of reverse proxy and base url in doc:
```
location /lanraragi {
    rewrite             ^/lanraragi(.*)$ $1 last;
    proxy_pass          http://0.0.0.0:3000;
    proxy_http_version  1.1;
    proxy_set_header    Upgrade     $http_upgrade;
    proxy_set_header    Connection  $connection_upgrade;
}
```

After checking all discussions and PRs timeline, I realized that it might be fixed like this:
```
location /lanraragi/ {                              # the location should end with slash
    proxy_pass          http://0.0.0.0:3000/;       # the upstream should also end with slash
                                                    #   it makes Nginx removes base url prefix
                                                    #   before passing requests to upstream
    proxy_http_version  1.1;
    proxy_set_header    Upgrade     $http_upgrade;
    proxy_set_header    Connection  "upgrade";      # $connection_upgrade is not configured by default
}
```
And it works after I used my patched configuration.

It may be an option to update the documentation(or after more volunteers and tests? I'm not sure).

- No convenient way to change `base_url_path` in `lrr.conf` when deploy LANraragi with docker

To deploy LANraragi with base url, it is required to change field `base_url_path` in `lrr.conf`. 

In the current version, the docker of LANraragi declare 4 volumes to mount:
> LANraragi/tools/build/docker/Dockerfile
```
...
# Persistent volumes
VOLUME [ "/home/koyomi/lanraragi/content" ]
VOLUME [ "/home/koyomi/lanraragi/thumb" ]
VOLUME [ "/home/koyomi/lanraragi/database"]
VOLUME [ "/home/koyomi/lanraragi/lib/LANraragi/Plugin/Sideloaded" ]
...
```
This means that if you want to use base url and choose docker to deploy server, you can not finish setup permanently, since you will lost `lrr.conf` after update.

And my fixed patch is to create a `lrr.conf` on the host machine and mount it to `/home/koyomi/lanraragi/lrr.conf` manually(Not elegant but effective).

A better way is to offer a `ENV` var like `BASE_URL` in Dockerfile and apply it into `lrr.conf` during build.

Hope all this will be helpful.
