### ISSUE TITLE
[Bug] Auto-plugin not respecting cooldown parameter

### ISSUE THREAD

**Issue by Mayriad** [Difegue/LANraragi#374]
**LRR Version and OS**

LANraragi for Windows 0.7.5 (MSI installer) on Microsoft Windows 10 build 19042.685. Archives are located on a NAS and accessed via a mount point in the content folder. Please refer to #274 my big list of LRR bugs and suggestions to see more details. Some problems may be caused by my relatively awkward setup.

**Bug Details**

I tested the `E-Hentai` plugin, and the (fairly) newly added `cooldown` parameter for metadata plugins is effective in batch tagging, but does not seem to apply to auto-plugin, which means the metadata plugin will not sleep between requests at all if you let auto-plugin tag archives as they are added. Indeed, when I tested it, I quickly got banned after maybe 500 archives.

[A user got temporarily banned](https://forums.e-hentai.org/index.php?showtopic=243403), likely twice in quick succession, when he used LRR to tag his archives. I think it was caused by auto-plugin, but I will ask him whether he actually used batch tagging, which would mean the 4 second cooldown is in fact not safe enough.

Edit: I see the final comments for #350 mentioned this issue and you said it is caused by parallel archive additions and you have not made a multi-process timer yet. Does that confirm this issue? Before you can fix it, it would be better to warn users of this potential problem with auto-plugin and recommend them to use batch tagging instead.

**Comment by Difegue** [comment]
Yup it's true, currently auto-plugin doesn't respect the cooldown parameter very well as it now goes through the Minion worker pool, which is inherently multi-process.  

I'm considering officially making the cooldown stuff only work in batch tagging, since properly implementing the cooldowns in auto would probably just be a mess.

**Comment by Difegue** [comment]
Took another look at this and yep, I'm just gonna stop applying `cooldown` outside of Batch Tagging for now.  

I think the issue with bans should be handled by better informing the user instead of trying to do this automagically -- I'd like to do that through a better OOBE experience, aka https://github.com/Difegue/LANraragi/issues/297.  
Telling the user he should look at Batch Tagging instead of Auto-Plugin if he has 500+ archives ready to import sounds reasonable.

(tbh this problem only really happens with EH, and the built-in plugin already slows down when encountering the ban warnings.)
