### ISSUE TITLE
[Bounty - 25$ atm] FAKKU Plugin Metadata Crawler

### ISSUE THREAD

**Issue by EvilKing3** [Difegue/LANraragi#384]
I want to suggest a nice feature to crawl metadata from FAKKU official website, the best thing will be to use the automatic search for metadata based on the standard name that rbot2000 use, example: [Aiya] Someone I Love (COMIC Kairakuten 2020-06).zip
Even a search based on URL input manually would be good enough, but it will kinda difficult for 5.6k chapters, and 1k doujins to do >_<
Another thing is that FAKKU hides some results (loli) if you are not logged in, but they don't have that many so it could be kinda skipped, but would be really nice if added as a login plugin.

**Comment by Difegue** [comment]
I personally don't have a fakku account and don't plan on getting one/implementing this.  
Wouldn't the chaika plugin fulfill your needs, since it already mirrors fakku's metadata?

**Comment by EvilKing3** [comment]
You are correct it seems to get all the datas from FAKKU, but for some reasons I doesn't get the artist, I tested with a FAKKU book and a single chapter..

**Comment by Difegue** [comment]
Hm, iirc the chaika plugin does pick up artists when present - Do you have a sample file I could use to try reproducing this?  

If your files all have the artist in their filename, I recommend you enable Auto-Tag before importing them in LRR so that it can at least be picked up that way.

**Comment by EvilKing3** [comment]
Ok found what was the problem, I was using Auto-Tag, it added not only the artist but a bunch of stuff useless, so I deleted it, and searched metadata with chaika after, doing so it excluded the already added artist from the title. So I ended up with no artist..
So I think you were right there is no need for a FAKKU only plugin, chaika does the trick.
Can I ask you directly another question, I installed LANraragi on Unraid with Docker, during the tests I messed up few things, so deleted all the archives, but I can't delete the thumb folder and it seems that I can't do it directly because the thumb folder and sub folder and files have different permission (from windows it says you need the authorization from Unix User\9001) I wanted to know if it's possible to generate thumbnails without the permissions so I can delete them from windows.
In the end I managed to delete all of the test archives thumbnails by changing permission from unraid console..
It would be a great thing to add an option that can delete thumbnails automatically when the archive is deleted.
Thanks again for this amazing gem.
P.S. Kaiki best girl.

**Comment by Difegue** [comment]
Auto-deletion of thumbnails has been added in https://github.com/Difegue/LANraragi/commit/e38df233c0ec9c8147167f13fff81ce1b2526feb recently so you'll get that in a future release. :) Glad you got stuff working otherwise!

**Comment by Difegue** [comment]
![fe2785a206daeec125fc84e482fadc13fd344b75424943abc3ec8e6a4774d9d0](https://user-images.githubusercontent.com/8237712/111159370-52c40280-8599-11eb-87ca-a37c5e633934.gif)

There's been a regain of interest in this issue due to the nexus/cafe shutdowns.  
I don't find parser work particularly exciting as-is so it's a perfect time to try something new 👀  

If you want a metadata crawler for FAKKU, feel free to pledge some money in this associated bountysource:  
https://www.bountysource.com/issues/97137401-fakku-plugin-metadata-crawler
The bounty is only collected on completion of the issue, so I feel this is a better model than baiting for donations and then doing nothing.  

More money = better support, of course. I don't have specific numbers in mind yet but a bare-bones implementation probably wouldn't have login support.

**Comment by Difegue** [comment]
$20 has been donated through non-bountysource means for this, so I'll try to get it done for the next release in a bare-bones way.

**Comment by Difegue** [comment]
Here's said bare-bones implementation:

* No login support
* Support for changing archive title
* Uses the basic fakku search page with your archive title since the API has apprently been removed ages ago (lmao)

A possible improvement would be to use the /suggest endpoint the site uses internally for search bar autosuggestions (it works better than the search page itself, I checked).
I couldn't leverage it as-is without jumping through cookie bullshit so w/e dropped
