### ISSUE TITLE
Shinobu getting confused when ID is in file name.

### ISSUE THREAD

**Issue by Nixis198** [Difegue/LANraragi#385]
**LRR Version and OS**
LRR Version: 0.7.5 - "Underground"
OS: UNRAID
Install Method: Docker

**Bug Details**
If the ID of the manga is the first thing in the file title Shinobu will use that as the manga name. IE. if i download let's say https://nhentai.net/g/342540/ it will be saved in a zip folder called "342540. [cabin] Love Divided Between a Rock and a Hard Place Ch.1[English] [K&S]". If I then take that zip folder and put it in LRR's content folder it will show up as "342540." If I then try to use the nhentai plugin to get tags for it it will either not find a nhentai page for it or will not be the right tags.

If I manually remove the "342540. " from the name of the zip file everything works perfectly. But I am unable to do this for my all my files.

**Matching Logs**
Shinobu logs when I add a manga with the ID in the name:
[2021-01-04 01:42:00] [Shinobu] [info] Adding new file /home/koyomi/lanraragi/content/342540. [cabin] Love Divided Between a Rock and a Hard Place Ch.1[English] [K&S].zip with ID 2e5a6caaa10669e000d97be8159ed1b77a85d3e7

**Screenshots**
Here is a screenshot of what it looks like.
![Screenshot 2021-01-03 204306](https://user-images.githubusercontent.com/29938035/103494392-ad581a00-4e04-11eb-8903-a25eed30d600.jpg)

**Comment by Nixis198** [comment]
I ended up making a [plugin ](https://github.com/Nixis198/nHentai-lookup-using-Hdoujin/blob/main/nHentaiLookupUsingHdoujin.pm) that reads the url from the info.txt file then pulls the tags and title from nhentai.net. It was my first time writing in perl and I know it can be better but from my testing it works. If you want to include it as plugin that comes with it just ask me to open a pull request.

**Comment by Difegue** [comment]
Great work! 👍 It's a bit rough around the edges but if it got you setup that's all that matters.  

As you've probably seen, the current nHentai plugin is a bit dumb as it only does a text search with the name of the zip.  
If the `(id). [(artist)] (name).zip` syntax is the default for stuff downloaded from nH, it'd be interesting to update the stock plugin to first try getting the ID from the filename(using what you wrote [here basically](https://github.com/Nixis198/nHentai-lookup-using-Hdoujin/blob/aeb0f12158695232e78b9f1b620b77f23efbd66b/nHentaiLookupUsingHdoujin.pm#L83)), then fallback to the existing search mechanism.  

I won't accept a PR for an extra plugin since it's a bit too similar to stock, but if you feel up for doing what I wrote above, I'd certainly merge that. 👀

**Comment by Difegue** [comment]
I've moved auto-parsing to a plugin and made it so it won't be enabled by default for new users.  
I still think the stock NH plugin could be improved to try detecting GIDs in the filename and using them instead of doing a text search, but as far as this issue's concerned it's essentially done. 😤
