### ISSUE TITLE
[Feature Request] Add support for AVIF images

### ISSUE THREAD

**Issue by ccvelandres** [Difegue/LANraragi#389]
Add support for AVIF images. AVIF images in archives are not detected when adding new archives.

**Comment by Difegue** [comment]
Support is easy enough to add on my end(and seems to work on browsers), but there are some gotchas:  
* AVIF support in ImageMagick is from v7 onwards: The current homebrew formula still uses [v6](https://formulae.brew.sh/formula/lanraragi) and would need an upgrade.
* Mobile browsers have spotty support for AVIF at the time being, but I don't think that's too much of an issue - users should expect that stuff when using newfangled image formats. 😁
* Tachiyomi and other external clients will probably choke on those images for the time being? Not sure.

Bonus good news: since magick uses `libheif` for both AVIF and HEIF, I could probably add support for both formats at once once this is cleared up.

**Comment by Difegue** [comment]
I've unlocked both HEIF/HEIC and AVIF as of the latest commit. Some caveats:  

## HEIC  

HEIC support in thumbnails should work even with Magick 6.9.  

There's absolutely no browser support (lmao), so if you want to display HEIC content in the web reader I suggest using the "Resize Images" feature to convert them to jpg with magick dynamically:  
![image](https://user-images.githubusercontent.com/8237712/109434169-3b6f0c00-7a14-11eb-8cc4-8c9e11550a6d.png)


## AVIF  

AVIF support in thumbnails needs ImageMagick v7 with `libheif` installed.

MS Edge doesn't support displaying the format, Chrome(supposedly) does.
You may encounter display issues on Firefox if you don't set the matching pref in about:config:  
![image](https://user-images.githubusercontent.com/8237712/109433946-25148080-7a13-11eb-86cd-fca90e9ca636.png)
