### ISSUE TITLE
Switch to a "streaming-type" extraction model for reading

### ISSUE THREAD

**Issue by darkred3** [Difegue/LANraragi#399]
Whenever I try to open a slightly larger gallery of up to 200 pages it takes at least 30 seconds or more. This can be circumvented by clicking on the archive again, but then only a small percentage of the pages are shown and the page needs to be refreshed again and again until all pages are loaded.
I take it that the entire archive is being indexed before opening it which is insanely inefficient. As with other image reading programs, it should be fairly easy to open galleries instantaneously and have the pages and thumbnails be loaded consecutively in the background instead.

**Comment by Difegue** [comment]
Initial archive extraction is one of the few parts of the app still running on the old single-transaction model: Opening `reader?id=xxx` checks server-side if the file is already extracted to the temporary folder, and extracts it during the HTTP request if it's not.  
This is why opening the link again sorta works, since the first request is basically busy doing the extracting, and the second one is just reaping the benefits for free. (But in an incomplete way, since the extraction is not over)  

This could very much be improved by hooking into `libarchive` directly instead of using the current abstraction libraries, since it can totally do streaming file list and extraction. I wouldn't quite call it ["fairly easy"](https://metacpan.org/pod/Archive::Libarchive::XS) though.  

I'd like to improve on this eventually (especially since the abstraction libs are getting old and require some extra jank to work properly on macOS/homebrew), but as caveman-tier as the current approach is, it only really chokes on big tanks so it's not very high priority.

**Comment by Difegue** [comment]
Extra implementation nuggets:  

- The API endpoints can entirely work the same with a streaming approach, so there should be no adaptation work for external clients.
-  `/api/extract` would just return the filelist parsed from the archive directly, instead of the current method of looking in the temporary folder. The method name becomes a bit weird as a consequence, but that can be deprecated/changed in due time.
- `/api/page` would be where the performance tradeoff lies, since it'd dynamically poke the archive on each call to extract the required file. I'd probably leverage the existing temporary folder stuff, so that only the first call for a given page does an extract.

**Comment by Difegue** [comment]
The workflow has been rebuilt as of the latest commit:

* `/api/extract` (now dubbed `/api/pages` but I'm leaving the old endpoint in for backwards compatibility) now fires a background Minion job to extract the archive, and uses at the same time a brand new Libarchive interface to return the list of files, directly streamed off the Archive. (This works great for zip, haven't tested rar too much yet)
* `/api/page` now checks if the desired page exists (as it mightve been extracted by the background job already), and if it doesn't, extracts it on the fly.  

There are some timing considerations with this new method (If the background job is currently extracting a page and we want to serve it, we have to make sure it's fully extracted before serving), but early testing seems to work great! This should bring awesome performance improvements to most third-party clients as well.
