### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by darkred3** [Difegue/LANraragi#400]
"Fit to Screen" scales all images to a measly 575px width while "Force Full Width" scales all images to screen size, including upscaling low quality images. Both of these options are less than optimal.

Sadpanda has the option to display images in several resolutions namely: 2400x, 1600x, 1280x, 980x and 780x
Having an option to set images to the preferred resolution (while not upscaling any images!!) would be nice. Alternatively, it might be even better if one could just input a custom width resolution instead.

Should be very easy to implement too.

**Comment by Difegue** [comment]
Sadpanda's support is more focused towards serving different sizes of the same image to save on bandwidth -- I have a similar feature in place with the auto-quality crush and file size threshold options.  

Past that though, the reader always serves the highest quality picture available, and all resizing is done on the browser side only.  
Users can basically use whatever sizes they want instead of the current ones through css/custom theming, so I only provide simple defaults/options for the time being.

Images currently show at 1200px wide by default:  
```
div.sni {
    max-width: 1200px;
}
```  
This is probably what you'd want configurable?
Fit to screen just uses your browser's height or width, so for a 1080p fullscreen you do end up around 575px in landscape.

**Comment by darkred3** [comment]
> This is probably what you'd want configurable?

Yes, that's correct. I know that the reader always serves the original images that are then resized to 1200px by default. Making this value configurable would be awesome!

**Comment by Difegue** [comment]
Haven't forgotten about this btw, did some studying and I'm probably going to revamp the reader options to fall more in line with what mangadex does:  
![image](https://user-images.githubusercontent.com/8237712/111034583-afe37b00-8416-11eb-8daf-8509516e2eb4.png)  

Most of those options are already possible in the current reader, but I do prefer the way they expose it in that screenshot. 😁

**Comment by darkred3** [comment]
Oh yeah, the way MD handles it is pretty neat. Will you add the Long strip option too?

**Comment by Difegue** [comment]
Long strip falls under https://github.com/Difegue/LANraragi/issues/242 I believe and is a bit harder to do (not by much since as you can see there's already a userscript for it), so I won't put it in the initial scope here.

**Comment by Difegue** [comment]
🎉
![image](https://user-images.githubusercontent.com/8237712/112389356-e5c90f00-8cf4-11eb-88f7-b7d3d9a3da30.png)

**Comment by darkred3** [comment]
Looking good!

If you intend to implement more or improve on existing reader features in the future you might also want to take the guyamoe reader as an example besides mangadex. It's got **a lot** of features, including long strip mode, and is open source at github.
https://github.com/appu1232/guyamoe
https://guya.moe/read/manga/Oshi-no-Ko/36/1/
