### ISSUE TITLE
Unicode is not displayed correctly in some places

### ISSUE THREAD

**Issue by pastalian** [Difegue/LANraragi#414]
**LRR Version and OS**
dev-4172e92, debian container

**Bug Details**
There are some places where unicode is not displayed correctly.

* Logs
* Filename Parsing
  * When generating tags containing multibyte characters with this plugin in Edit Mode (only first time, save & reload will fix it)
  * Some characters like ★ (U+2605) and 々 (U+3005) will completely break the tag (reload will not fix it)

**Matching Logs**
```
[Minion] [info] Processing uploaded file /tmp/6LUeaFARLj/[ã¦ãã¨âã¦ãã¨] æ¥æ¬èªâæ¥æ¬èª.tar...
[Archive] [debug] File Name: [ã¦ãã¨âã¦ãã¨] æ¥æ¬èªâæ¥æ¬èª
[Archive] [debug] Filesystem Path: /LANraragi/content/[ã¦ãã¨âã¦ãã¨] æ¥æ¬èªâæ¥æ¬èª.tar
[regexparse] [info] Sending the following tags to LRR: artist:ã¦ãã¨âã¦ãã¨
[regexparse] [info] Parsed title is æ¥æ¬èªâæ¥æ¬èª
```

**Screenshots**
![bugged](https://user-images.githubusercontent.com/28638872/109372582-95c17d00-78ed-11eb-9fa9-42d060c8de1f.png)

**Comment by pastalian** [comment]
I guess using `redis_decode()` will fix above 2 bugs?
Apparently file paths are intentionally not encoded, but I think the log output should be encoded (there's no point in an unreadable log).

**Comment by Difegue** [comment]
Yup, seems like moving regexparse around from internal code to the plugin system 

The logs being garbled depend on where the newly uploaded file is coming from.  
Files coming from Shinobu/file watching will show correctly, but files coming from Minion/web uploads won't. (Probably because of the necessary `utf8::downgrade` workaround)

 `redis_decode` is basically the magic function for everything unicode now, but I don't like overusing it either since logging fully-decoded text can spew out `wide character in say` warnings from Perl, and it does overall muddy up the logic since what you're displaying isn't exactly what's being used in code...  

I've added decodes to the Minion side of logging for now, so even if it garbles up a bit further down the chain users can still figure it out. Not sure why it **does** garble at all, since everything else seems to be working fine. 🤔
The proper fix would be to make sure filenames from Minion are encoded properly -- `utf8::downgrade` seems to work for everything except terminal/log display though

**Comment by pastalian** [comment]
Thanks, but there is one part that is forgotten :cry:  https://github.com/Difegue/LANraragi/blob/78fccb09cc4230b9097277daed238f31929c5d9a/lib/LANraragi/Utils/Database.pm#L33-L34
