### ISSUE TITLE
Windows Installer Encoding Issue

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#42]
Hello. 
LANraragi does not seem to handle Unicode filenames and throws the following error
> [Shinobu] [warn] Deleting ID 35896a024099377df6bd295f52220ba7132bf659 - File D:/Portable/LANraragi/lanraragi/content/(COMIC1☆13)  [星屑コメット (柚月ゆあ)] COMET_12 (Fate Grand Order).zip cannot be found.
> threadId=00002AC8:tick=6261515:Unknown codepage=932

**Comment by xd1986k** [comment]
Tried both. Dosen't fix the error.
Adding chcp 65001 did fix display of unicode characters inside the prompt however.

**Comment by Difegue** [comment]
Right. After a bit [more searching](https://stackoverflow.com/questions/15224400/perl-on-windows-problems-with-encoding), it turns out the problem doesn't lie in the windows commandline, but in perl not being aware we're using a windows codepage.  

The above commit fixed the issue on my dev machine (was able to upload/read/delete an archive with Unicode filenames without trouble), I'll update the Windows .zip on the release page to include the hotfix.

**Comment by xd1986k** [comment]
Didn't fix the error for me. 
[2018-05-03 01:39:39] [Shinobu] [info] Done!
[2018-05-03 01:39:39] [Shinobu] [warn] Deleting ID 51050a66fd9170c94d3fbc9c4f60da8e6715b482 - File D:/Portable/LANraragi/lanraragi/content/(COMIC1ÂÂ13) [ÂfÂBÂGÂbÂvÂHÂ[ (ÂÂ ÂÃ©ÂÃÂ[ÂÃ)] ÂyÂ[ÂpÂ[ÂoÂbÂNÂEÂÂÂCÂ^Â[ACT.00 (ÂÃ¡ÂÂ¦ÂÃÂÂ¢ÂÃÂÂÂÃÂÃ§ÂÃÂÂ©ÂÂ½).zip cannot be found.
[2018-05-03 01:39:39] [Shinobu] [info] Archive count (1) has changed since last cached value (0) OR rebuild has been forced (flag value = 0), rebuilding...
[2018-05-03 01:39:34] [Auto-Tagger] [info] Executing enabled plugins on archive with id 51050a66fd9170c94d3fbc9c4f60da8e6715b482.
[2018-05-03 01:39:34] [Shinobu] [info] Adding new file D:/Portable/LANraragi/lanraragi/content/(COMIC1ÂÂ13) [ÂfÂBÂGÂbÂvÂHÂ[ (ÂÂ ÂÃ©ÂÃÂ[ÂÃ)] ÂyÂ[ÂpÂ[ÂoÂbÂNÂEÂÂÂCÂ^Â[ACT.00 (ÂÃ¡ÂÂ¦ÂÃÂÂ¢ÂÃÂÂÂÃÂÃ§ÂÃÂÂ©ÂÂ½).zip with ID 51050a66fd9170c94d3fbc9c4f60da8e6715b482

**Comment by Difegue** [comment]
well shit - maybe I need to specifically scan for the used codepage at runtime and use that. What a pain. 

Going to need some basic diagnostic info:  

* Windows version (I'm using 10 which I suspect is much better at handling Unicode)
* Default codepage (you can get that by typing `chcp` in a command line )

**Comment by xd1986k** [comment]
Windows 10 1709
chcp 932

**Comment by Difegue** [comment]
Right, 932 is Microsoft's version of SHIFT-JIS.  
I recall it handling filepaths differently from the others, so that probably explains it.  

You can try changing line 8 of `lanraragi/lib/LANraragi.pm` on your own from `cp65001` to `cp932` and see if it fixes the problem. If my diagnostic is correct, it should. 

I'll add in codepage detection tomorrow - luckily there's a [CPAN package](https://metacpan.org/pod/Win32::Codepage) for that.

**Comment by xd1986k** [comment]
Did not fix the issue.

**Comment by Difegue** [comment]
¯\\\_(ツ)\_/¯
I'm officially out of ideas.  
I'll switch my dev machine to 932 to do some detailed testing, but for now I guess you'll have to rename your files or switch locales.

**Comment by xd1986k** [comment]
Eh, no worries. I still got my vagrant install until this starts working.

**Comment by Difegue** [comment]
I tried a few things on a Shift-JIS Win10 VM, but there's no real easy way to get out of this one that I know of. 

(On the bright side, I did port the QuickStarter to a Powershell script while doing my testing, so that'll probably be in 0.5.3. Doesn't fix the problem here, though.)

Our internal Unicode handling is pretty much rock-solid as of now, but the real issue mostly lies in the Windows console itself and how [Windows Perl ports](https://www.windowsperl.com/2014/02/20/dealing-with-code-pages/) have trouble dealing with it.

It mostly works with ASCII locales, but Shift-JIS and a few others introduce changes to the console that throws us off path.
There are [seemingly ways](https://metacpan.org/pod/ShiftJIS::CP932::MapUTF) to deal with codepages, but I'm not going to bloat the main codebase with edge cases for them, as the native Windows version still remains secondary* and there's multiple ways to run LRR on those Windows systems, like Vagrant/Docker.


\* As a matter of fact, Mojolicious [dropped Windows support as of last month but it still works so w/e](https://metacpan.org/changes/distribution/Mojolicious)
