### ISSUE TITLE
Version v0.7.9 runs with an error in docker ,the error content is reader?id=5a3042009e55decedccb098383fce7cf8581a46e:123 Uncaught ReferenceError: Reader is not defined

### ISSUE THREAD

**Issue by zyx134** [Difegue/LANraragi#495]
<!-- hol up senpai have you checked out the GH Discussions first ? 
Your issue/idea might've already been reported by someone else! 🐱‍👤
https://github.com/Difegue/LANraragi/discussions
->

**LRR Version and OS**
Please tell which version you're running, as well as your OS and installation method. (Windows, Docker, Native)

**Bug Details**
Please detail the bug here. 

**Matching Logs**
Post any logs you have encountered when reproducing the bug.  
If possible, switch the app to Debug Mode in order to have more logs.

**Screenshots**

**Comment by Difegue** [comment]
Thanks for this report. I've had a few other users mention it, and I believe it's caused by `||=` not being very well accepted by all browsers. (Despite the [Mozilla compat report](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment#browser_compatibility) saying otherwise)  

Which browser are you using? I've had some people experiencing the issue with firefox but not chrome and vice-versa so it's a bit muddied at the moment.

**Comment by zyx134** [comment]
I have this problem with chrome and safari

**Comment by Difegue** [comment]
The reader should work fine with `old` browsers again with this change in the nightly Docker images.

**Comment by zyx134** [comment]
thinks
