### ISSUE TITLE
Namespace Support and Comic Preview in Thumbnail view + Wrapping in List View

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#5]
A few suggestions/questions.
1. Do you plan to add namespace support at some point?
2. Modify the metadata regex so that bracket enclosed content at the end of file name is parsed as language. 
3. A metadata overview popup having content formatted similar to EX's metadata page in thumbnail mode.
4. Associating an archive with Ex or another metadata site's ID so there is easier duplicate detection + future metadata calls.
5. Storing both Japanese and Romaji versions of the title/author/circle on metadata collection.
6. Parse (ongoing) and (complete) into the title field after title.

**Comment by Difegue** [comment]
This is a big one! Going over the list:

1. Gonna sound retarded here, but what do you mean by namespace support? 
2. The metadata regex is meant to be (kinda) easily modifiable by the end user. I don't plan on modifying its current default behavior for now, since it's pretty equivalent to the file name convention used everywhere. (language is normally already supported)
3. This is actually a pretty good idea, since popup support is already there and thumbnail mode isn't very informative in its current state. Noted.
4. Way too much work for little returns, imo. 
5. Metadata collection(except for tags) depends entirely on the file name, so if it doesn't have romaji, it ain't gonna pop up. What "could" be done is extend tag lookup to also complete title/author/circle, but this is rather low priority. 
6. See 2. Past a certain point it's pretty hard to account for all the possible variations in filenames, sadly.

**Comment by xd1986k** [comment]
-I'm sorry for not being clearer. I meant tag namespaces like "female:unusual pupils", "misc:3d", "Artist:Blah Blah", "Circle:0101" and the like. Seems to be an easier way to add more information without the need for extra columns. The current metadata fetching behavior seems to scrub them and only fetch the base tags.
-Some archives absolutely refuse to fetch metadata in spite of inputting correct metadata in title and author so a manual url input for metadata fetching would be nice for those cases. 
-5: Low priority is better than the alternative :).

**Comment by Difegue** [comment]
Oh, those. The current tag fetcher pretty much gets tags as-is from the APIs. I'd have to dive back into their documentation and see where they store namespaces. If that's not too much of a pain, there's no problem for me adding a checkbox during tag import to keep them.

About archive URLs, I can easily add a manual url input instead of using the title/author search. (which is kinda finicky on E-H, I'll give you that.)

**Comment by xd1986k** [comment]
Thank you. 
One more suggestion comes to mind. Support for metadata import from Comic Rack.ini, CBL, [eze](https://dnsev-h.github.io/eze/) JSON inside archives.

**Comment by Difegue** [comment]
Closing this for now, will open single issues for the remaining suggestions.
