### ISSUE TITLE
Incorrect total entries count

### ISSUE THREAD

**Issue by pandafeliz** [Difegue/LANraragi#510]
**LRR Version and OS**
Version 0.8.0, "Black Tie White Noise" OS: Windows 10

**Bug Details**
The total entries count shows a number above my current filecount, I executed the clean database and reset search cache commands but it remains the same. This was working correctly in 0.7.9 so not sure if is a visual bug or old entries that were deleted before and the clean database command can't catch.

**Matching Logs**
None

**Screenshots**

This is my current filecount
![XYplorer_CRs1bxATmi](https://user-images.githubusercontent.com/72732463/135078682-5668bf5d-675f-4a6b-a910-8f1b730e0f6b.png)

and this is what is displayed in the application without any filters applied

![chrome_3e1Z9NXATb](https://user-images.githubusercontent.com/72732463/135079283-1aeb646e-ecd7-45e7-b6bf-ea380d609d1e.png)

as you can see the total filecount goes up but the filtered count is the correct one.

**Comment by Difegue** [comment]
I'm aware of this issue; I made the `total` count use the keycount of the redis database so I can save an extra DB call, but it's slightly incorrect due to the DB having a few more keys for configuration. https://github.com/Difegue/LANraragi/blob/7d23e8a3cf4c9e6268744f25126d9e2b33d7c2c3/lib/LANraragi/Model/Search.pm#L34 

The total count is just used for display so there shouldn't be undeletable entries strewn about or anything like that. I'll figure out a better way to handle this in a next release.

**Comment by pandafeliz** [comment]
alright, thanks.
