### ISSUE TITLE
Total entries doesn't match the showing archives and actual archives inside the folder.

### ISSUE THREAD

**Issue by EvilKing3** [Difegue/LANraragi#563]
**LRR Version and OS**
Latest, Docker install on UNRaid with custom template

**Bug Details**
Total entries doesn't matches archives, I've 9155 cbz files, the system says that the total entries are way more: 9902 and it shows only 9144 even without any filters, is possible to trim the entries that are not linked to any archive (I tried clean DB, didn't change anything) and to show what archives are not linked (11 are missing in my case, but I added them all togheter so I have no clue what are the ones missing)

**Screenshots**
![image](https://user-images.githubusercontent.com/5150545/145441915-1a213937-5e45-4bca-9c64-69416fd6db10.png)

**Comment by AbyssalMonkey** [comment]
![Too many](https://user-images.githubusercontent.com/29171166/145517283-261dc8c4-69cc-4981-8020-d9a645622d86.JPG)
I have the same problem in the opposite direction.

**Comment by EvilKing3** [comment]
@AbyssalMonkey that's even more strange, I managed to the issue but it took a lot to figure it out:
the total entries are generated per archive (or should) but if you rename the archives it will add +1, in my case I renamed a tons of archives, and this got solved by simply restarting the Shinobu Watcher, I did few test and apparently if you rename an archive, and then name it back it will disappear from the library and it will counts 2 total entries, to solve this you need to first clean DB and then restart the Shinobu Watcher, the manga will re-appear on the library and the entries will get fixed.
While testing I noticed that adding to many cbz to the archive will crash Shinobu in some case (over 1000 files at the time) and in other case (always if not crash) it will count thousand of records less, in this case the only fix I found was to restart the docker application entirely.

Last thing apparently the FAKKU metadata seems to not work properly at all, both on batch and single filter, for most cases it does but for case with "chapter - 1" like this one: https://www.fakku.net/search/shady%20dealings%20chapter most tags will be taken from the last one ( chapter - 4 in that case) this seems to happens to every single series with multiple chapters in the name and not only that but even in case 1 author has many works in some cases it picks another work from that author instead the correct one (I noticed this thanks to the incorrect Magazine tags in a lot of them) I tried to manually fix it, but after 1k edits I gave up.

**Comment by Difegue** [comment]
Thanks for the detailed report.  

I'm suspecting this is due to the filewatcher not cleaning up its internal filemap properly when rename operations happen. Restarting it prompts a filemap rebuild, which as you saw fixes the issue.    
The total count is currently based on said filemap, so you shouldn't be too worried if it drifts from the real count a bit.  

I'm hoping to resolve this alongside #555, since adding more search-specific tables _should_ allow for more precision.

**Comment by Difegue** [comment]
As for the FAKKU crawler, I should probably stick this somewhere in its description but it's as accurate as it gets given what we're working with. (the F! search in this case)  

You might notice that searching for https://www.fakku.net/search/shady%20dealings%20chapter%201 to get a specific chapter doesn't work; I recommend using the Chaika plugin first and only falling back to FAKKU if you can't get your tags any other way.

**Comment by Difegue** [comment]
With #555, we now use the new title/ID index instead of the filemap to determine total count.  

This won't really be more accurate since if you delete files from your filesystem without going through the app, the ID will remain in the DB, leading to a different count from what's really on your FS.  
But it will at least always represent the total n° of IDs stored in the database, instead of fluctuating based on weird filesystem events.  

I don't plan on doing anything else about this issue. 🤷

**Comment by webbster64** [comment]
I have somewhat the same problem, I've noticed that some archives aren't added to the gallery, I've added them to the folder and it not showing in the UI
