### ISSUE TITLE
[Suggestion] Option to hide the carousel view in Index

### ISSUE THREAD

**Issue by PasserDreamer** [Difegue/LANraragi#567]
**Please describe your suggestion, and the problem it'd solve.**
Please add an option for show/hide "ancient chinese lithographies" in the settings.
Thanks.
![123](https://user-images.githubusercontent.com/30385417/146185596-75338ba4-b653-4d76-a7cc-f892b4ad8da6.png)

**Comment by PasserDreamer** [comment]
Yes, I personally prefer simple clean and sad panda style UI.
The carousel is more like a complicated design IMO.

**Comment by pandafeliz** [comment]
the carousel seems to choke if you have a lot of untagged archives since it loads them all, and appears to be the same for the new filter, I remember the time I tried it caused a memory leak in the browser since I have around 3k or so archives still marked with the new tag.

I tried hiding it but it seems it still loads the data even collapsed and it doesn't remember the hiding status when you use the search.

**Comment by AbyssalMonkey** [comment]
> I tried hiding it but ... it doesn't remember the hiding status when you use the search.

This is the most annoying thing to me.  I use LRR to act as a host for my phone, and use external readers, since unfortunately, phone browsers are still prone to breaking at the slightest touch compared to desktop and phone apps.  As a result, if I'm using the LRR webapp, it's purely for database management, and the carousel is not helpful with that.  So having to collapse it every time I perform a search is tedious.

**Comment by Difegue** [comment]
As of the latest commit, collapsing the carousel will now be remembered on further loads (I should've added this on initial release, but hindsight is 10/10 as they say), and the required API endpoints won't be called if it's collapsed/uninitialized.  

As mentioned before, I don't plan on adding functionality to hide the carousel altogether; The redesigned index takes less vertical space than the previous version even with it present. You can use custom CSS on your end if you really want it gone I guess!
