### ISSUE TITLE
Filter by pages count

### ISSUE THREAD

**Issue by duckimann** [Difegue/LANraragi#586]
**Please describe your suggestion, and the problem it'd solve.**

Pls add "filter by pages count" like nHentai did

"You can search for galleries with a specific number of pages with **pages:20**, or with a page range: **pages:>20** **pages:<=30**."

**Comment by ndbiaw** [comment]
Unavailable. The page number can only be known when decompressing the archive, which will increase the server load considerably just because of the small feature.
Counting files in archive is also not available, as it may contain other files, or the PDF file is divided into multiple pages.

**Comment by duckimann** [comment]
We can have the pages count in the metadata (info.json) file right? I think the filter by pages count should only available when the archive is parsed by internal plugins.

**Comment by ndbiaw** [comment]
> We can have the pages count in the metadata (info.json) file right? I think the filter by pages count should only available when the archive is parsed by internal plugins.

Not all repositories have and use info files, and once you've added the metadata you can sort by page number, so what's the point of creating this issue?

**Comment by RePod** [comment]
If the equivalent of `unzip -l zip.zip` or `7z l seven.7z` is cheaper than an extraction it should be easy to approximate how many pages there are until an extraction occurs later.

The server expects certain filetypes (which I believe get lumped together when "presented") so irrelevant ones do not matter. For PDFs assume at least one page.

**Comment by Difegue** [comment]
Since the switch to the new libarchive bindings, it's possible to get the file count (and size) fast enough:  https://github.com/Difegue/LANraragi/blob/6c1b241d99d90cba669c89df9ca99b3ad4a5bfa4/lib/LANraragi/Utils/Archive.pm#L198

This function is already used in the revamped extract/thumbnail system, and could also be leveraged to fill the pagecount field in the database on initial file indexation.  
I haven't gotten to adding this to Shinobu yet, but it's something I'd like to do since having page counts only after a first decompression isn't very good UX.  

Past that, extending search to take page counts into account is a good enhancement, but it certainly needs the above work done first.

**Comment by Difegue** [comment]
This'll be in 0.8.9 -- You can search for galleries with a specific number of pages with `pages:20`, or with a page range: `pages:>20, pages:<=30`.
