### ISSUE TITLE
Add a "Summary" field

### ISSUE THREAD

**Issue by LovingCivilian** [Difegue/LANraragi#588]
im kinda of a perfectionist, so i tends to collect every piece of metadata i could find.
unfortunately one of them is the "Summary" which currently there's no easy way to add it.

i think adding a "Summary" field that supports multi-line text would truly make lanraragi a more complete archival.

**Comment by ndbiaw** [comment]
with the current interface, it's hard to add them anywhere
but it's also a good idea

**Comment by LovingCivilian** [comment]
I've tried editing the page HTML to get a feel for how it would look.

![chrome_20220209231149](https://user-images.githubusercontent.com/16726932/153284313-00d55903-827a-4bd3-a260-6dd2318ed32c.png)

![image](https://user-images.githubusercontent.com/16726932/153284459-7df0666f-039c-4a32-aff0-5a2682013694.png)

And yeah I can see that some people might think it adds too much space, and they're right.
But for me, its a compromise I'm willing to take for the sake of having a complete view of the metadata.

**Comment by Difegue** [comment]
This'd require a new database field, since there's no way multi-line summaries can fit in the tags area.  

I'm not explicitly against adding this! (even though I'd personally have little use for it)  
I don't think it'd even be very complicated, just some busywork to update the Edit metadata pages (and the plugin system to make updating summaries from plugins possible)

**Comment by Difegue** [comment]
Implemented.  
![image](https://github.com/Difegue/LANraragi/assets/8237712/0d6d4a99-655b-468d-8197-5dcbb315e780)  

This comes with the required amenities to update summaries from edit and plugins, and backup/restore them.  
I haven't gone ahead and updated any of the plugins, however.
