### ISSUE TITLE
Special Symbol Display Error

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#6]
The following symbol "〇" is displayed as "ããã"

**Comment by Difegue** [comment]
Works on my side (Tested by quickly editing an archive metadata to include the symbol). 
Sure sounds like yet another perl unicode issue, though.

**Comment by xd1986k** [comment]
After checking it works for me that way as well. However importing a file with the above symbol in it's file name gives the problem.

**Comment by Difegue** [comment]
Yep, since metadata is on a per-file hash basis, if the file is the exact same it'll be cached on the redis side. 
Gonna check the base import script - might need an extra utf8 decode or something

**Comment by Difegue** [comment]
With an archive called "aaaaaa〇〇〇.zip" :

Method | Result
------------ | -------------
Uploading through the Upload Archive form | OK
Editing metadata  | OK
Dragging the archive into the content folder and letting the autouploader sort it out | it's fucked fellas

All of those use the same base functions, but the filename wasn't prepped correctly with the autouploader method. Seems fixed with f835a550d11f1439a1ff365ba89845353ce07fd1 . I'm getting pretty good at untangling those utf8 issues tbh

**Comment by Difegue** [comment]
NB: I'd advise against updating from the bare repo until 0.4 is out and documented, due to the NPM dependency change. Nothing's stopping you from just copying the affected ajax.pl file though, that should work as-is.
