### ISSUE TITLE
Change database type?

### ISSUE THREAD

**Issue by ndbiaw** [Difegue/LANraragi#648]
**Please describe your suggestion, and the problem it'd solve.**
Change the database type of LRR.

**Additional context**

Redis takes up too much RAM. Collections with too many archives cannot run smoothly. I have a collection of more than 10k+ archives and Redis frequently gets killed by the system because it takes up too much RAM, and when using maxmemory I lose data. It's not okay in the slightest. Although it is fast, the cost to run it is not okay.

**Comment by Difegue** [comment]
lol no

**Comment by Difegue** [comment]
A more serious answer for other people that would encounter this issue:

A lot of the current design of LRR is directly written on top of Redis instead of using an ORM (that might've been a mistake but go tell that to 2014 me), so switching the backend database would be a non-trivial task that'd imply rewriting half the app.

And I certainly don't have it in me to do that for the time being. If someone were to fork the code, rewrite it to sit on top of sqlite with proper migration steps and make a gigaton-sized PR? Sure! :^)
