### ISSUE TITLE
EH language tag needs to be deleted twice to get removed from metadata.

### ISSUE THREAD

**Issue by soarpasser** [Difegue/LANraragi#651]
**LRR Version and OS**
0.8.5 Windows msi

**Bug Details**
As stated in title - 
When you use the "E-Hentai" plugin to apply tags to a certain gallery, the language tag needs to be deleted twice to disappear from the metadata.

Reproducing this issue:
1. pick any gallery
![image](https://user-images.githubusercontent.com/74951691/176778942-9c67666c-92ec-4c0c-a574-9e5adcd796e3.png)
2. enter a EH gallery link, tags gets applied.
![image](https://user-images.githubusercontent.com/74951691/176779157-2ceacdf3-883a-4fae-890f-c03bb2aba739.png)
3. clicks the × next to the language tag I wish to remove, and click on "save metadata".
![image](https://user-images.githubusercontent.com/74951691/176779337-942c696f-71b6-41d5-bed8-67e326faee72.png)
4. refreshes the page - the tag that I wanted to remove is still there.
![image](https://user-images.githubusercontent.com/74951691/176779438-e3274d93-681e-49dc-8de2-1d58bfbf6fdf.png)
5. repeat step 3 and refresh again, now the tag actually gets removed.
![image](https://user-images.githubusercontent.com/74951691/176779514-046a54ab-4bcb-45bd-a695-ec4c4ab9b3a6.png)

Not sure if this is a plugin-related issue or an issue with the application. Figured I'd report it here anyways.

**Matching Logs**
Nothing of note.

**Comment by Difegue** [comment]
👋 I'm not sure this is an issue with the actual metadata storage, it might just be browser cache showing you the old tag even though it's been removed. (There's some specific code to prevent this but it might still happen on specific browsers?)  

Can you try refreshing between each step with **Ctrl+F5** instead of just F5 and see if that changes anything? Thanks!

**Comment by soarpasser** [comment]
> 

In fact I do use Ctrl+F5 when refreshing - I have it bound to a button on my mouse.
In case it helps, browser used here is Firefox 64bit version 102.0

**Comment by Difegue** [comment]
Good to know, that probably does mean that there's an issue with the metadata system. I'll try to look it up.

**Comment by Difegue** [comment]
Narrowing things down, this isn't a specific bug with the metadata system, plugin or language tags, but with the edit form: It seems that deleting the **first tag** added by a plugin in the list after **applying a plugin** never works.  

Refreshing the edit form, then deleting the tag works. This is because plugin runs have a leading space, which is then misinterpreted by tagger.js when we delete the tag. 🫠  
This will be fixed in the next release, thanks for the report!
