### ISSUE TITLE
Sort/display archives by date added to folder?

### ISSUE THREAD

**Issue by Singularity12** [Difegue/LANraragi#67]
Hey, wanted to say first of all thanks for all the work you've put into LRR, it's made it so much easier to keep track of my collection!

Title is pretty self-explanatory, apologize if I missed a setting somewhere. I like to sort by date added in Explorer because I don't remember all the names of the newest doujins I've downloaded. An option for this in LRR would be awesome. Thanks!

**Comment by Difegue** [comment]
Hey there, thanks for the support.  

I don't store added dates in the database, but the "New" flag is set for all archives you added without opening them.  
This flag sadly gets a bit useless as your collection grows, since you're not going to go through 10 pages to look for all the archives that have it on.  

I don't really want to replace it by date added either, as it's A) more work, B) not a metadata I find useful in the long term (one'd basically just use it to see what was uploaded last as you're saying)  
What I can do instead is add a filter to the index that only shows archives that have the "New" flag active.

**Comment by rettisances** [comment]
Would it be possible if a filter called "latest" could be implemented that has a list of archives descending in order of being added? Something similar to the "Latest Comics" feature in Ubooquity perhaps.

**Comment by Singularity12** [comment]
A way to kind of "mark all as read"/clear all New flags for when the database is built and a filter to only show archives with the New flag would completely work for me.

**Comment by Difegue** [comment]
Done as of the latest commit. The filter has been added to the main index page, and the clear flags button to configuration.

I also took the opportunity to do a little UX revamp on buttons in the config panels.
![image](https://user-images.githubusercontent.com/8237712/49812930-c47fc700-fd66-11e8-95e9-f3dc7e043d82.png)
