### ISSUE TITLE
Not sure if bug or I'm too stupid to understand the tagging

### ISSUE THREAD

**Issue by jmhickman** [Difegue/LANraragi#69]
**LRR Version and OS**
v0.5.5
Ubuntu LXC container running Debian buster

**Bug Details**
Archives I import seem to get tags even though I have the automatic tagging turned off and all plugins disabled. I get stuff with nonsense tags like shown below.

I've actually had this issue ever since I started using LRR, but I'm lazy and hadn't reported it yet.

I'd like for the archives to not be tagged at all. Even better would be a plugin that just added an 'unread' tag, since the "new" label doesn't seem to work for me all the time (it's missing in that screenshot for example, even though those chapters are new uploads and I haven't viewed them yet...)

**Matching Logs**
No relevant logs. The Plugins view doesn't show anything about those two archives in the picture at all.

**Screenshots**
![badtags](https://user-images.githubusercontent.com/6581761/49716047-1a922480-fc18-11e8-99fe-b428a1f3b40b.jpg)
![options1](https://user-images.githubusercontent.com/6581761/49716357-203c3a00-fc19-11e8-9ea3-5475d6985141.jpg)
![options2](https://user-images.githubusercontent.com/6581761/49716362-2205fd80-fc19-11e8-9a3a-883b7c4e8851.jpg)

**Comment by Difegue** [comment]
I've noticed some issues with the "new" flag not being applied/removed properly - Fixes are already in the nightlies but since I haven't made a release in a while you probably don't have them.  
In similar fashion, the plugin you want is [already in the nightlies as well.](https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Plugin/CopyTags.pm)  

As for the tags you're having, these come from the automatic filename regex parsing when an archive is uploaded. There's no way to currently disable this, but it could be added in.  

I haven't had much time to work on LRR recently, but hopefully I'll be able to get a 0.5.6 out with all this stuff before the new year.

**Comment by jmhickman** [comment]
Alrighty, thanks for clearing that up for me, and I look forward to the new release.
