### ISSUE TITLE
New archive seems broken?

### ISSUE THREAD

**Issue by xiazeyu** [Difegue/LANraragi#769]
It seems that the new archive will not remove books that just watched. There will be “new” archives with reading progress 0/xx

This can be temporary fixed by deleting any book.

**Comment by xiazeyu** [comment]
what does "new archive indicators" means? Mark every book read? But that will cause me losing track of my already read book.

I haven't tried to disable server-side reading progression. Is there any possible connections?

**Comment by Clevlandpink** [comment]
I am also having this issue. After completing an archive it is not removed from the _New Archives_ section.

Clearing the new archive indicators did not help. I am using server side reading progress.

When I clean the database or delete an archive it will update all previously read archives and remove them from _New Archives_.

This problem was not present when I started using LANraragi and I believe it started a couple of updates ago.

**Comment by Difegue** [comment]
Thanks for the info - I'll try taking a look.

**Comment by Difegue** [comment]
Search cache not being busted when isnew would be modified - Fixed now. Thanks!
