### ISSUE TITLE
Make "Save archive title" plugin setting handled by LRR

### ISSUE THREAD

**Issue by siliconfeces** [Difegue/LANraragi#789]
**Please describe your suggestion, and the problem it'd solve.**
Most metadata plugins have a "Save archive title" setting. This could be handled by LRR instead, avoiding quite a bit of repeated functionality inside the plugins.

This setting does not make sense for the "Tag Copier" and "Add Timestamp tag" plugins though. Either `plugin_info` could return a flag whether or not it supports archive handling, or it could just be ignored.

**Comment by Difegue** [comment]
This makes sense to me, although I'm not sure where to show the then global setting for saving/modifying archive titles -- Having it in plugin configuration at the top makes sense, but all the other global toggles are in the main settings page..

**Comment by siliconfeces** [comment]
I'd vote for putting at the top of the plugin configuration, mostly because there's no good existing section in the settings page. Shouldn't be TOO hard to move it later though, if LRR ends up getting a bunch of related settings in the future.

**Comment by Difegue** [comment]
Implemented this - The toggle lives here for the time being.  
![image](https://github.com/Difegue/LANraragi/assets/8237712/a46ef862-38e4-4f5b-9832-036c10684d17)

**Comment by chu-shen** [comment]
> Implemented this - The toggle lives here for the time being.
> 
> ![image](https://user-images.githubusercontent.com/8237712/278485758-a46ef862-38e4-4f5b-9832-036c10684d17.png)
> 
> The way I went with it is that every plugin can send `title` if they want, and the server decides whether or not to apply the change based on the toggle.

Thanks for your nice work, but this change break my archive title😭

This change makes it impossible for me to only select certain plugins to save the title. I can't control it.

I want to know if the titles returned by all plugins are in order and which plugin's title is ultimately written into the database. 

Because not all plugins return satisfactory title, such as `EHentai`.

---

What about this case: 
- archive: `(AC2) [比村乳業 (比村奇石)] 月曜日のたわわ そのX [中国翻訳].zip`
- plugin execution priority: high > Filename Parsing > E-Hentai > low
- The title we want is `月曜日のたわわ そのX`

titles returned by all plugins:
|Save archive title|Yes|No|
|---|---|---|
|Filename Parsing|月曜日のたわわ そのX||
|E-Hentai|(AC2) [比村乳業 (比村奇石)] 月曜日のたわわ そのX [中国翻訳]||

final title: 
|Save archive title|Filename Parsing Yes|Filename Parsing No|
|---|---|---|
|E-Hentai Yes|(AC2) [比村乳業 (比村奇石)] 月曜日のたわわ そのX [中国翻訳]|(AC2) [比村乳業 (比村奇石)] 月曜日のたわわ そのX [中国翻訳]|
|E-Hentai No|月曜日のたわわ そのX||

- previous configuration: `Filename Parsing: Yes`+`E-Hentai: No`: `月曜日のたわわ そのX` ✅
- after this change: `Save archive title: Yes`: `(AC2) [比村乳業 (比村奇石)] 月曜日のたわわ そのX [中国翻訳]` ❎

---

Now I have rolled back the E-Hentai plugin to the old version and turn off `Save archive title`. Any suggestions?

**Comment by Difegue** [comment]
Thanks for the details -- Currently Filename Parsing is hardcoded to always run first as it's often helpful to clean up titles before doing text searches with other plugins.  

I've been wanting to implement configurable plugin execution order for a while but haven't gotten to it. I think it'd help you here? Since you could just run filename parsing after EH.
