### ISSUE TITLE
Extra metadata from plugins

### ISSUE THREAD

**Issue by koma-cute** [Difegue/LANraragi#81]
When pulling information for a plugin, try and get as much information from the page, other than just tag information. For example, things like the upload date, uploader username, and most importantly (when logged in) the favorite category that the gallery is in.

**Comment by Difegue** [comment]
I personally won't do this one, since I don't really care for uploaders and dates.  
The plugin API does make this easy to do however -- The current HDoujin plugin(not written by me) does add uploaders if I recall correctly.  

The category thing can be useful, but I don't use this part of E-H at all so I actually have no idea how it works and where to scrap the data. 🤷‍♀️

**Comment by koma-cute** [comment]
Actually, looking at the (minimal) [EH API docs](https://ehwiki.org/wiki/API), there doesn't actually seem to be a way to get favorite categories without scraping HTML, which is probably something you don't want to get into.

**Comment by Difegue** [comment]
The EH API is really limited, we actually already have to scrape HTML for logins and search.
It's basically only good for the last step, i.e getting tags from a gallery ID.

**Comment by Difegue** [comment]
Done in recent versions of the E-H plugin. (As much as possible that is)
