### ISSUE TITLE
E*H File Search / Similarity Search

### ISSUE THREAD

**Issue by ripe-mangos** [Difegue/LANraragi#815]
**Please describe your suggestion, and the problem it'd solve.**
Torrents are a great way to obtain galleries without spending hard-earned GP. However, they can't be automagically tagged. E\*H has a file search feature which could be used to match covers against E\*H galleries.

**Additional context**

The file is uploaded via a `POST` to `https://upld.exhentai.org/upld/image_lookup.php`. The request was multipart-encoded:
 - `sfile`- the file
 - `fs_similar`- checkbox for similarity
 - `fs_covers`- checkbox for covers only

This endpoint responds with a `302 FOUND` and redirect.

Test 1 (similarity enabled): `https://exhentai.org/?f_shash=[hex-encoded string];[hex-encoded string];[hex-encoded string]&fs_from=[filename]&fs_similar=on&fs_covers=on`
Test 2 (similarity disabled): `https://exhentai.org/?f_shash=[hex-encoded string]&fs_from=[filename]&fs_covers=on`
Both tests with the same image.

As multiple galleries may share a given cover image, I'd recommend also checking titles.

**Comment by Difegue** [comment]
👋 The current E-H plugin already makes use of `fs_similar` : https://github.com/Difegue/LANraragi/blob/f9b765132729faf0879b64b909ea8956c8c48366/lib/LANraragi/Plugin/Metadata/EHentai.pm#L136  

This uses an internally-computed cover hash instead of uploading to EH, but I believe the result should be the same. Is there anything in your ask that isn't fulfilled by this feature? 

(sorry for having taken so long to get to this!)
