### ISSUE TITLE
Request a rating system

### ISSUE THREAD

**Issue by kokkeng1** [Difegue/LANraragi#873]
I checked it on the discussion board, but it's too old an issue

**Please describe your suggestion, and the problem it'd solve.**

First of all, thank you for developing a good app.
I saw a comment saying that the rating system has low priority and should be managed with tags.
But it's very strange that the Content Manager app doesn't have a scoring system. I want you to know that there is a demand to distinguish whether this was good or not by horoscope because a person's memory is limited.
It is very cumbersome to modify the tag you suggested before. Since the app doesn't have a tag preset, I always have to add an emoji to modify it.

**Additional context**
I request modify the score with a click in the Archive Overview menu.

**Comment by Difegue** [comment]
👋 I still maintain this can and should be handled thru a tag instead of spinning off yet another DB field, as it makes sorting by rating "just work" with the current design.  

A rating control could be added to the edit UI to quickly add/update/remove a matching `rating:` tag, I suppose.

**Comment by alok5050** [comment]
Hey, I am new to this and would like to contribute. Do you have any pointers on how to get started with this issue?

**Comment by Difegue** [comment]
Sure! Thanks for stepping up 🙏 I believe this can be done thru frontend only. 
You can use Codespaces to spin up a development version of the app, and just upload any random pdf or zip with one image in it to get an entry you can add metadata to. 

You can look at https://github.com/Difegue/LANraragi/blob/dev/templates/edit.html.tt2 and https://github.com/Difegue/LANraragi/blob/dev/public/js/edit.js for the HTML/JS code used by the edit metadata page.  

Tags in LRR are in a simple comma-delimited format, so implementing this should be as easy as adding a rating control that when interacted with, adds a `rating:⭐⭐⭐⭐,` tag to the textfield. If a rating tag is already present, it should probably update it with the matching star count.  
I suppose the rating should go from 1 to 5 stars, and selecting 0 stars should remove the tag from the textfield.

**Comment by chu-shen** [comment]
Below is an example that works for me by [editing the UI](https://github.com/chu-shen/LANraragi/blob/4ee1b9e04866f7602eab7445f4f09c67dd1270de/templates/index.html.tt2#L247) and using [plugins](https://github.com/chu-shen/LANraragi/blob/4ee1b9e04866f7602eab7445f4f09c67dd1270de/lib/LANraragi/Plugin/Metadata/Rating.pm)

<img width="387" alt="chrome_oD0xFBmmrE" src="https://github.com/Difegue/LANraragi/assets/45256288/4792071b-8e76-41f8-8312-e54ea7ec6997">

But there is still some questions
- Currently, updates are not supported.
- I also added a `Comment` tag. Since all tags in LRR are stored in the "Tag" field and separated by commas, `Comment` tag cannot contain commas. I'm not sure if this approach is suitable...

---

As an aside, if you use this new [react-based PWA client](https://github.com/hibikikuze4dan/lanraragi-react-web), you may like [this Rating&Comment](https://github.com/hibikikuze4dan/lanraragi-react-web/issues/6)

![](https://github.com/chu-shen/lanraragi-react-web/raw/feat-ratingAndcomment/legend-Tony.png)

**Comment by Difegue** [comment]
👋 Just popping in to mention a comment field would be added by https://github.com/Difegue/LANraragi/issues/588.  

In case anyone wants to work on that...

**Comment by Difegue** [comment]
Implemented in https://github.com/Difegue/LANraragi/pull/1079.
