### ISSUE TITLE
Implement inotify watching for archives

### ISSUE THREAD

**Issue by koma-cute** [Difegue/LANraragi#89]
Running LANraragi on a small box, I noticed every time its interval check fired, the CPU spiked to ~25% or so. Looking at the logs, I can't see any mention of new archives, so can only assume the big CPU usage is coming from the `get_archive_list` function that is unconditionally run every interval.

Implementing an inotify watcher should help with this issue (and be a lot more straightforward now Windows is dropped), though I'm not really sure why a file listing is hitting this hard either anyway. Doing a simple `ls` in my folder even multiple times a second is using a fraction of CPU Shinobu does when scanning every 5.

**Comment by Difegue** [comment]
`get_archive_list` does a bit more than basic file listing, since it also goes through subdirectories and applies a quick regex filter to only get archive files.  
Still though, this is something that could be done way better than a dumb time interval -- I agree that a inotify watcher would be the best way forward for now.

**Comment by Difegue** [comment]
Got a tiny bit to write still (subdirectories within a subdirectory added post-launch), but this is pretty much happening now.  
I entirely expect things to break at this point and will need to test this pretty extensively.

**Comment by Difegue** [comment]
A test with 1800 archives showed a Shinobu boot time of around 40 seconds(main app is already up and running during that time period), which I think is acceptable.
