### ISSUE TITLE
Cannot search using a language other than English

### ISSUE THREAD

**Issue by nyanpasunyan** [Difegue/LANraragi#915]
After importing the file, even if the file name is in Japanese, it cannot be searched in a language other than English, such as Japanese.

**Comment by cazendium** [comment]
You may need to provide more information.

- Do your archives have tags for languages, like language:Japanese?
- Is it language:Japanese or language:日本語?

Archives need to be provided metadata that you enter yourself or you use plugins to do it for you when importing or doing batch operations.

Since you mention file names, I’m assuming you are using the file name regex plugin. And if you’re getting your content from eh, then Japanese archives don’t state they’re in the Japanese language in their file or archive names.

But it also sounds like you are about to search for it in English, then you are gonna have to change your language tags to Japanese characters if that’s the case.

**Comment by nyanpasunyan** [comment]
For example, if I import a file named (C102) [Brio (ぷよちゃ)] ぷよちゃンネル.zip, lanraragi displays (C102) [Brio (ぷよちゃ)] ぷよちゃンネル. If I search for Brio, I can retrieve the file, but if I search for ぷよちゃ, I won't get any results.

**Comment by nyanpasunyan** [comment]
> For example, if I import a file named (C102) [Brio (ぷよちゃ)] ぷよちゃンネル.zip, lanraragi displays (C102) [Brio (ぷよちゃ)] ぷよちゃンネル. If I search for Brio, I can retrieve the file, but if I search for ぷよちゃ, I won't get any results.

**Comment by cazendium** [comment]
> For example, if I import a file named (C102) [Brio (ぷよちゃ)] ぷよちゃンネル.zip, lanraragi displays (C102) [Brio (ぷよちゃ)] ぷよちゃンネル. If I search for Brio, I can retrieve the file, but if I search for ぷよちゃ, I won't get any results.

I copy and pasted your example file name onto an archive of mine and parsed it. And I was able to search Brio and ぷよちゃ.

Although, my archive parsed that example into tags, so that could explain why. Did you add tags to it?

**Comment by Difegue** [comment]
Looks like #849. Can you confirm this is the same issue?  

> It seems that recent versions of LRR just don't like searching brand new archives with non-English characters in the filename. Curiously, the search function will start working again once the archive's metadata has been modified in some way.

**Comment by niepan11** [comment]
I have the same problem.I can't use Japanese in the title for searching.

**Comment by Difegue** [comment]
Fixed by https://github.com/Difegue/LANraragi/commit/f52b9904d9389e6e3ec13cae81f60bd6156d5026 .
