### ISSUE TITLE
[Feature Request] Add 'History' column at the top

### ISSUE THREAD

**Issue by millionart** [Difegue/LANraragi#935]
![image](https://github.com/Difegue/LANraragi/assets/7535532/9affd806-cc1d-475b-966d-3168219d90e2)

Please add a History option below the location in the screenshot, sometimes I forget what I read the other day XD

**Comment by Difegue** [comment]
That'd be covered through #911 I believe

**Comment by Difegue** [comment]
![image](https://github.com/Difegue/LANraragi/assets/8237712/1e0c4792-3bb4-465f-8957-3db7fead32f9)

**Comment by Difegue** [comment]
I've added the "On Deck" section I was thinking of in #911 .  

This will show the last opened files, ordered by time. (Now due to current limitations it will show even files that have been read to completion.. But the UI will have the little crown icon anyway)

![image](https://github.com/Difegue/LANraragi/assets/8237712/1e0c4792-3bb4-465f-8957-3db7fead32f9)
